CritterList.class: CritterList.java NodeGeneric.class
	javac CritterList.java

LLString.class: LLString.java NodeGeneric.class
	javac LLString.java

LLGeneric.class: LLGeneric.java NodeGeneric.class
	javac LLGeneric.java

NodeGeneric.class: NodeGeneric.java
	javac NodeGeneric.java

run: CritterList.class
	java CritterList

clean:
	rm *.class
